export type MarketerStatus = "available" | "claimed" | "active-bid";

export interface Marketer {
  id: string;
  name: string;
  company: string;
  role: string;
  category: "CMO" | "Growth" | "Brand" | "Performance";
  avatar: string;
  status: MarketerStatus;
}

export const marketers: Marketer[] = [
  {
    id: "1",
    name: "Sarah Chen",
    company: "Glossier",
    role: "Chief Marketing Officer",
    category: "CMO",
    avatar: "https://i.pravatar.cc/150?img=1",
    status: "claimed",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    company: "Peloton",
    role: "VP of Growth",
    category: "Growth",
    avatar: "https://i.pravatar.cc/150?img=2",
    status: "available",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    company: "Away",
    role: "Head of Brand",
    category: "Brand",
    avatar: "https://i.pravatar.cc/150?img=3",
    status: "active-bid",
  },
  {
    id: "4",
    name: "David Kim",
    company: "Casper",
    role: "Director of Performance",
    category: "Performance",
    avatar: "https://i.pravatar.cc/150?img=4",
    status: "available",
  },
  {
    id: "5",
    name: "Alexandra Petrov",
    company: "Warby Parker",
    role: "CMO",
    category: "CMO",
    avatar: "https://i.pravatar.cc/150?img=5",
    status: "claimed",
  },
  {
    id: "6",
    name: "James Wright",
    company: "Allbirds",
    role: "Growth Lead",
    category: "Growth",
    avatar: "https://i.pravatar.cc/150?img=6",
    status: "available",
  },
  {
    id: "7",
    name: "Mia Thompson",
    company: "Rent the Runway",
    role: "Brand Director",
    category: "Brand",
    avatar: "https://i.pravatar.cc/150?img=7",
    status: "available",
  },
  {
    id: "8",
    name: "Nathan Park",
    company: "Harry's",
    role: "Performance Marketing Lead",
    category: "Performance",
    avatar: "https://i.pravatar.cc/150?img=8",
    status: "active-bid",
  },
  {
    id: "9",
    name: "Olivia Santos",
    company: "Sweetgreen",
    role: "Chief Marketing Officer",
    category: "CMO",
    avatar: "https://i.pravatar.cc/150?img=9",
    status: "available",
  },
  {
    id: "10",
    name: "Chris Anderson",
    company: "Outdoor Voices",
    role: "VP Growth Marketing",
    category: "Growth",
    avatar: "https://i.pravatar.cc/150?img=10",
    status: "claimed",
  },
  {
    id: "11",
    name: "Jessica Liu",
    company: "Blue Apron",
    role: "Head of Brand Strategy",
    category: "Brand",
    avatar: "https://i.pravatar.cc/150?img=11",
    status: "available",
  },
  {
    id: "12",
    name: "Ryan Mitchell",
    company: "Hims & Hers",
    role: "Director of Paid Media",
    category: "Performance",
    avatar: "https://i.pravatar.cc/150?img=12",
    status: "available",
  },
  {
    id: "13",
    name: "Amanda Foster",
    company: "Everlane",
    role: "CMO",
    category: "CMO",
    avatar: "https://i.pravatar.cc/150?img=13",
    status: "active-bid",
  },
  {
    id: "14",
    name: "Derek Huang",
    company: "WeWork",
    role: "Growth Marketing Manager",
    category: "Growth",
    avatar: "https://i.pravatar.cc/150?img=14",
    status: "available",
  },
  {
    id: "15",
    name: "Sophia Martinez",
    company: "Mirror",
    role: "Creative Director",
    category: "Brand",
    avatar: "https://i.pravatar.cc/150?img=15",
    status: "claimed",
  },
  {
    id: "16",
    name: "Tyler Brooks",
    company: "Ro",
    role: "Head of Performance",
    category: "Performance",
    avatar: "https://i.pravatar.cc/150?img=16",
    status: "available",
  },
  {
    id: "17",
    name: "Rachel Green",
    company: "Bombas",
    role: "VP of Marketing",
    category: "CMO",
    avatar: "https://i.pravatar.cc/150?img=17",
    status: "available",
  },
  {
    id: "18",
    name: "Kevin Patel",
    company: "Compass",
    role: "Growth Lead",
    category: "Growth",
    avatar: "https://i.pravatar.cc/150?img=18",
    status: "available",
  },
  {
    id: "19",
    name: "Lauren Scott",
    company: "Reformation",
    role: "Brand Marketing Director",
    category: "Brand",
    avatar: "https://i.pravatar.cc/150?img=19",
    status: "active-bid",
  },
  {
    id: "20",
    name: "Michael Torres",
    company: "Slice",
    role: "Performance Marketing Lead",
    category: "Performance",
    avatar: "https://i.pravatar.cc/150?img=20",
    status: "claimed",
  },
];
